spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    master:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite:///home/zjy/workspace/mycode/java_ToolSiteMvc4J/web/target/classes/db/app.db
      username:
    slave:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite:///home/zjy/workspace/mycode/java_ToolSiteMvc4J/web/target/classes/db/app.db
      username:
    migration:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite:///home/zjy/workspace/mycode/java_ToolSiteMvc4J/web/target/classes/db/app.db
      username:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    interceptors: com.zjy.mvc.common.sql.SqlPrint

server:
  error:
    include-exception: true
    include-message: always
  port: 8088

pagehelper:
  helperDialect: sqlite

log:
  path: d:/tmp/logs
  level: INFO