spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    master:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite://D:/tmp/app.db
      username:
    slave:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite://D:/tmp/app.db
      username:
    migration:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite://D:/tmp/app.db
      username:

server:
  error:
    include-exception: true
    include-message: always

pagehelper:
  helperDialect: sqlite

log:
  path: d:/tmp/logs
  level: INFO