spring:
#  elasticsearch:
#    rest:
#      uris: 127.0.0.1:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
##      cluster-nodes: hadoop137:9300,hadoop138:9300,hadoop139:9300