spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints:
            - 127.0.0.1:9300
          use-ssl: false
#          username:
#          password:
# 非starter配置
es:
  protocol: http
  host: 127.0.0.1
  port: 9200
  username:
  password:
server:
  port: 8098