spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      jdbcUrl: jdbc:mysql://localhost:3306/toolsitemvc4j?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      jdbcUrl: jdbc:mysql://localhost:3306/salvedb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
logging:
  level:
    com:
      zjy: debug